"""
1000+ test questions across 10 mental health topics.
Each entry: (question_text, expected_classification)
Classifications: "happy", "sad", "critical", "out_of_context"
"""

# TOPIC 1: DEPRESSION & SADNESS (120 questions)
depression = [
    ("i feel so sad today", "sad"), ("mujhe bohot dukh ho raha hai", "sad"),
    ("life mein koi khushi nahi hai", "sad"), ("i am depressed", "sad"),
    ("kuch bhi achha nahi lagta", "sad"), ("everything feels empty", "sad"),
    ("bohot low feel ho raha hai", "sad"), ("i feel so down", "sad"),
    ("mera mood bohot kharab hai", "sad"), ("nothing makes me happy anymore", "sad"),
    ("main bohot udas hu", "sad"), ("i feel worthless", "sad"),
    ("zindagi mein koi ras nahi raha", "sad"), ("i feel like crying all the time", "sad"),
    ("rona aa raha hai bas", "sad"), ("i feel so hopeless", "sad"),
    ("kuch karne ka man nahi karta", "sad"), ("i dont enjoy anything anymore", "sad"),
    ("bohot thak gaya hu mentally", "sad"), ("i feel numb inside", "sad"),
    ("andar se toot gaya hu", "sad"), ("i feel broken", "sad"),
    ("sab bekar lagta hai", "sad"), ("mujhe koi samajhta nahi", "sad"),
    ("nobody understands me", "sad"), ("i feel so alone in this world", "sad"),
    ("bohot akela feel ho raha hai", "sad"), ("i have no motivation", "sad"),
    ("mann nahi lagta kisi kaam mein", "sad"), ("i feel drained emotionally", "sad"),
    ("emotionally exhausted hu main", "sad"), ("i feel like a burden", "sad"),
    ("main sab pe bojh hu", "sad"), ("i feel invisible", "sad"),
    ("koi meri parwah nahi karta", "sad"), ("nobody cares about me", "sad"),
    ("i feel stuck in life", "sad"), ("zindagi mein aage nahi badh pa raha", "sad"),
    ("har din same lagta hai", "sad"), ("every day is the same struggle", "sad"),
    ("i cant stop crying", "sad"), ("ruk nahi raha rona", "sad"),
    ("bohot heavy feel ho raha hai", "sad"), ("my heart feels so heavy", "sad"),
    ("i feel suffocated", "sad"), ("gala ghut raha hai", "sad"),
    ("mujhe depression hai", "sad"), ("i think i have depression", "sad"),
    ("main bahut pareshan hu", "sad"), ("i am very disturbed", "sad"),
    ("bohot bura feel ho raha hai", "sad"), ("i feel terrible", "sad"),
    ("kuch bhi thik nahi hai", "sad"), ("nothing is going right", "sad"),
    ("mera koi nahi hai", "sad"), ("i have nobody", "sad"),
    ("bohot dard ho raha hai andar", "sad"), ("it hurts so much inside", "sad"),
    ("ro ro ke thak gaya hu", "sad"), ("i cried myself to sleep", "sad"),
    ("zindagi bohot mushkil hai", "sad"), ("life is so difficult", "sad"),
    ("main toot chuka hu", "sad"), ("i am shattered", "sad"),
    ("koi umeed nahi dikhti", "sad"), ("i see no hope", "sad"),
    ("sab kuch boring lagta hai", "sad"), ("everything feels meaningless", "sad"),
    ("mujhe khushi ki definition bhool gayi", "sad"), ("i forgot what happiness feels like", "sad"),
    ("main bohot kamzor feel kar raha hu", "sad"), ("i feel so weak", "sad"),
    ("dimaag mein bas negativity hai", "sad"), ("only negative thoughts in my mind", "sad"),
    ("bohot darr lagta hai mujhe", "sad"), ("i am scared of everything", "sad"),
    ("mann mein bohot ghabrahat hai", "sad"), ("i feel so anxious", "sad"),
    ("neend bhi nahi aati soch soch ke", "sad"), ("overthinking se neend nahi aati", "sad"),
    ("koi baat karne wala nahi hai", "sad"), ("i have no one to talk to", "sad"),
    ("main apne aap se nafrat karta hu", "sad"), ("i hate myself", "sad"),
    ("mujhse kuch nahi hota", "sad"), ("i cant do anything right", "sad"),
    ("har jagah fail ho raha hu", "sad"), ("i fail at everything", "sad"),
    ("bohot frustrated hu", "sad"), ("i am so frustrated with life", "sad"),
    ("mann mein bahut gadbad chal rahi hai", "sad"), ("my mind is a mess", "sad"),
    ("sab log khush hain bas main nahi", "sad"), ("everyone is happy except me", "sad"),
    ("mujhe lagta hai main pagal ho raha hu", "sad"), ("i feel like im going crazy", "sad"),
    ("dimag kaam nahi kar raha", "sad"), ("my brain has stopped working", "sad"),
    ("bohot irritated feel ho raha hai", "sad"), ("i am irritated all the time", "sad"),
    ("mood swings bohot hote hain", "sad"), ("my mood keeps changing", "sad"),
    ("aaj bahut bura din tha", "sad"), ("today was a terrible day", "sad"),
    ("kuch samajh nahi aa raha kya karu", "sad"), ("i dont know what to do with my life", "sad"),
    ("bohot helpless feel ho raha hai", "sad"), ("i feel so helpless", "sad"),
    ("mujhe lagta hai main kisi kaam ka nahi", "sad"), ("i feel useless", "sad"),
    ("puri duniya mere khilaf hai", "sad"), ("the whole world is against me", "sad"),
    ("mera dil toot gaya hai", "sad"), ("my heart is broken", "sad"),
    ("feelings express nahi ho rahi", "sad"), ("i cant express what i feel", "sad"),
    ("bahut bhari lag rahi hai zindagi", "sad"), ("life feels so heavy", "sad"),
    ("main khud se door hota ja raha hu", "sad"), ("i feel disconnected from myself", "sad"),
    ("sab kuch khatam sa lagta hai", "sad"), ("it feels like everything is ending", "sad"),
    ("bohot thaka hua hu har cheez se", "sad"), ("i am tired of everything", "sad"),
    ("mujhe apna future dark lagta hai", "sad"), ("i see darkness in my future", "sad"),
    ("bahut rona aata hai bina wajah", "sad"), ("i cry for no reason", "sad"),
]

# TOPIC 2: SUICIDAL THOUGHTS / CRISIS (120 questions)
crisis = [
    ("i want to die", "critical"), ("mujhe marna hai", "critical"),
    ("i want to kill myself", "critical"), ("main apni jaan de dunga", "critical"),
    ("i dont want to live anymore", "critical"), ("ab jeena nahi chahta", "critical"),
    ("i want to end my life", "critical"), ("zindagi khatam karna chahta hu", "critical"),
    ("i want to commit suicide", "critical"), ("mujhe suicide karna hai", "critical"),
    ("i will jump off the building", "critical"), ("chhat se kud jaunga", "critical"),
    ("i want to disappear forever", "critical"), ("hamesha ke liye gayab ho jana chahta hu", "critical"),
    ("i want to sleep and never wake up", "critical"), ("so jau aur kabhi na uthu", "critical"),
    ("nobody would miss me", "critical"), ("mera jaana kisi ko farak nahi padega", "critical"),
    ("the world is better without me", "critical"), ("duniya mere bina behtar hai", "critical"),
    ("i have no reason to live", "critical"), ("jeene ki koi wajah nahi hai", "critical"),
    ("i am planning to end it all", "critical"), ("sab khatam karne ka plan hai", "critical"),
    ("ab bardasht nahi hota", "critical"), ("i cant take it anymore", "critical"),
    ("i want to hurt myself", "critical"), ("main apne aap ko hurt karna chahta hu", "critical"),
    ("i have a suicide note ready", "critical"), ("maine suicide note likh liya hai", "critical"),
    ("i took pills", "critical"), ("maine goliyan kha li", "critical"),
    ("i cut myself", "critical"), ("maine apne aap ko kata hai", "critical"),
    ("maut aa jaye toh achha hai", "critical"), ("death would be a relief", "critical"),
    ("zindagi se tang aa gaya hu", "critical"), ("i am fed up with life", "critical"),
    ("mar jana better hai", "critical"), ("dying is better than living", "critical"),
    ("sab kuch chhodna chahta hu", "critical"), ("i want to leave everything", "critical"),
    ("give up kar diya maine", "critical"), ("i have given up on life", "critical"),
    ("mujhe zahar kha lena chahiye", "critical"), ("i should take poison", "critical"),
    ("kash main paida na hua hota", "critical"), ("i wish i was never born", "critical"),
    ("nahi jee sakta aur", "critical"), ("i cannot live anymore", "critical"),
    ("sab chhod ke jana chahta hu", "critical"), ("i want to leave everything behind", "critical"),
    ("alvida duniya", "critical"), ("goodbye cruel world", "critical"),
    ("jaan dena chahta hu", "critical"), ("i want to give up my life", "critical"),
    ("mar jaunga ek din", "critical"), ("i will die one day soon", "critical"),
    ("maut se darr nahi lagta ab", "critical"), ("i am not afraid of death anymore", "critical"),
    ("zeher kha lunga", "critical"), ("i will drink poison", "critical"),
    ("fanda laga lunga", "critical"), ("i will hang myself", "critical"),
    ("nadi mein kud jaunga", "critical"), ("i will jump in the river", "critical"),
    ("ab aur nahi jhela jata", "critical"), ("i cant endure this anymore", "critical"),
    ("jeene ka koi matlab nahi", "critical"), ("there is no meaning to life", "critical"),
    ("jina bekar hai", "critical"), ("living is pointless", "critical"),
    ("main khatam ho jaunga", "critical"), ("i will be finished", "critical"),
    ("sab kuch khatam karna hai", "critical"), ("i want to end everything", "critical"),
    ("final goodbye bol raha hu", "critical"), ("this is my final goodbye", "critical"),
    ("aakhri baar baat kar raha hu", "critical"), ("this is the last time we talk", "critical"),
    ("mujhe koi rok nahi sakta", "critical"), ("nobody can stop me now", "critical"),
    ("aaj raat ke baad sab khatam", "critical"), ("after tonight everything ends", "critical"),
    ("marna chahta hu bas", "critical"), ("i just want to die", "critical"),
    ("ab aur nahi", "critical"), ("no more of this", "critical"),
    ("i want to sucide", "critical"), ("mujhe sucide karna hai", "critical"),
    ("i wanna end it all bhai", "critical"), ("sab khatam kar dena chahta hu", "critical"),
    ("ma mar jau kiya", "critical"), ("should i kill myself", "critical"),
    ("life is not worth living", "critical"), ("jeena worth it nahi hai", "critical"),
    ("duniya chhod dunga", "critical"), ("i will leave this world", "critical"),
    ("so jau hamesha ke liye", "critical"), ("let me sleep forever", "critical"),
    ("i think ill sleep forever", "critical"), ("main hamesha so jaunga", "critical"),
    ("shayad yahi aakhri din hai", "critical"), ("maybe this is my last day", "critical"),
    ("it would be better if i was dead", "critical"), ("mera marna hi better hai", "critical"),
    ("mujhe ab jeena nahi hai", "critical"), ("i dont want to live", "critical"),
    ("jeene ka mann nahi hai", "critical"), ("jee nahi sakta main", "critical"),
    ("mar hi jata hu", "critical"), ("let me just die", "critical"),
    ("koi bachane wala nahi hai", "critical"), ("mujhe koi bacha nahi sakta", "critical"),
    ("sab kuch bekar hai jeena bekar hai", "critical"), ("everything is futile", "critical"),
    ("ab bas bohot ho gaya", "critical"), ("enough is enough", "critical"),
    ("ek aur din nahi jee sakta", "critical"), ("i cant survive another day", "critical"),
    ("main apna wajood khatam karna chahta hu", "critical"), ("i want to cease to exist", "critical"),
    ("zindagi ek saza hai", "critical"), ("life is a punishment", "critical"),
    ("duniya se jana hai mujhe", "critical"), ("i need to leave this world", "critical"),
]

# TOPIC 3: ANXIETY & STRESS (100 questions)
anxiety = [
    ("bohot stressed hu", "sad"), ("i am very stressed", "sad"),
    ("anxiety attack aa raha hai", "sad"), ("i am having an anxiety attack", "sad"),
    ("mann mein ghabrahat ho rahi hai", "sad"), ("i feel so anxious", "sad"),
    ("haath pair kaanp rahe hain", "sad"), ("my hands are trembling", "sad"),
    ("dil bohot zor se dhadak raha hai", "sad"), ("my heart is racing", "sad"),
    ("saans lena mushkil ho raha hai", "sad"), ("i cant breathe properly", "sad"),
    ("bohot tension ho rahi hai", "sad"), ("i am very tense", "sad"),
    ("panic attack aa raha hai", "sad"), ("i think im having a panic attack", "sad"),
    ("dar lag raha hai kuch hone ka", "sad"), ("i am afraid something bad will happen", "sad"),
    ("overthinking bohot ho rahi hai", "sad"), ("i cant stop overthinking", "sad"),
    ("future ke baare mein darr lagta hai", "sad"), ("i am scared about the future", "sad"),
    ("har cheez se darr lagta hai", "sad"), ("i am afraid of everything", "sad"),
    ("mann mein bahut bechainee hai", "sad"), ("i feel very restless", "sad"),
    ("concentrate nahi ho raha", "sad"), ("i cant focus on anything", "sad"),
    ("dimag mein hazar cheezein chal rahi hain", "sad"), ("my mind wont stop racing", "sad"),
    ("bohot nervous hu", "sad"), ("i am very nervous", "sad"),
    ("pet mein gadbad ho rahi hai stress se", "sad"), ("stress is affecting my stomach", "sad"),
    ("socially anxious feel hota hai", "sad"), ("i have social anxiety", "sad"),
    ("logo ke saamne jaane mein darr lagta hai", "sad"), ("i am afraid to face people", "sad"),
    ("kya hoga agar fail ho gaya", "sad"), ("what if i fail", "sad"),
    ("worst case scenario dimaag mein chalte rehte hain", "sad"), ("i keep thinking of worst scenarios", "sad"),
    ("bohot overwhelmed feel ho raha hai", "sad"), ("i feel completely overwhelmed", "sad"),
    ("sab kuch control se bahar ja raha hai", "sad"), ("everything is spiraling out of control", "sad"),
    ("itna pressure hai ki handle nahi hota", "sad"), ("the pressure is unbearable", "sad"),
    ("kal kya hoga pata nahi", "sad"), ("i dont know what tomorrow will bring", "sad"),
    ("bohot insecure feel hota hai", "sad"), ("i feel so insecure", "sad"),
    ("logon ke judgement se darr lagta hai", "sad"), ("i am scared of being judged", "sad"),
    ("presentation deni hai bohot darr lag raha hai", "sad"), ("scared of giving presentation", "sad"),
    ("interview hai bohot nervous hu", "sad"), ("very nervous about the interview", "sad"),
    ("perfectionism ki wajah se stress hai", "sad"), ("perfectionism is stressing me out", "sad"),
    ("deadlines ki wajah se pagal ho raha hu", "sad"), ("deadlines are driving me crazy", "sad"),
    ("multitask nahi ho pa raha", "sad"), ("i cant multitask", "sad"),
    ("workload bohot zyada hai", "sad"), ("too much workload", "sad"),
    ("burnout ho raha hai", "sad"), ("i am burning out", "sad"),
    ("rest karne ka time nahi milta", "sad"), ("no time to rest", "sad"),
    ("body mein tension feel ho rahi hai", "sad"), ("my body feels tense", "sad"),
    ("sar dard ho raha hai stress se", "sad"), ("i have a stress headache", "sad"),
    ("neend nahi aa rahi tension ki wajah se", "sad"), ("i cant sleep due to stress", "sad"),
    ("bohot irritable ho gaya hu", "sad"), ("i have become very irritable", "sad"),
    ("chhoti chhoti baaton pe gussa aa jata hai", "sad"), ("i get angry over small things", "sad"),
    ("mujhse galti ho jayegi darr lagta hai", "sad"), ("i am afraid i will make mistakes", "sad"),
    ("kuch bhi karne se pehle darr lagta hai", "sad"), ("i am afraid to do anything", "sad"),
    ("bohot self doubt hai", "sad"), ("i have a lot of self doubt", "sad"),
    ("khud pe bharosa nahi raha", "sad"), ("i have lost confidence in myself", "sad"),
    ("pura din anxious rehta hu", "sad"), ("i stay anxious the entire day", "sad"),
    ("raat ko bhi chain nahi milta", "sad"), ("no peace even at night", "sad"),
    ("dar ke mare kuch kar nahi pata", "sad"), ("fear paralyzes me", "sad"),
    ("jab bhi phone bajta hai darr lagta hai", "sad"), ("i get scared when phone rings", "sad"),
    ("crowd mein jaane se darr lagta hai", "sad"), ("i am scared of crowds", "sad"),
]

# TOPIC 4: ACADEMIC PRESSURE (100 questions)
academic = [
    ("exam mein fail ho gaya", "sad"), ("i failed my exam", "sad"),
    ("padhai mein man nahi lagta", "sad"), ("i cant focus on studies", "sad"),
    ("syllabus khatam nahi ho raha", "sad"), ("syllabus is not finishing", "sad"),
    ("marks bohot kam aaye", "sad"), ("i got very low marks", "sad"),
    ("cgpa gir gaya", "sad"), ("my cgpa dropped", "sad"),
    ("backlog lag gaya", "sad"), ("i got a backlog", "sad"),
    ("sab padh rahe hain main nahi", "sad"), ("everyone is studying except me", "sad"),
    ("result ka bohot darr hai", "sad"), ("i am scared of the result", "sad"),
    ("papa ko kya bataunga", "sad"), ("what will i tell my parents", "sad"),
    ("teachers ne daant diya", "sad"), ("my teacher scolded me", "sad"),
    ("class mein sabse peeche hu", "sad"), ("i am last in class", "sad"),
    ("kuch samajh nahi aata", "sad"), ("i dont understand anything", "sad"),
    ("padhai ka pressure bohot hai", "sad"), ("too much study pressure", "sad"),
    ("coaching bohot hectic hai", "sad"), ("coaching is very hectic", "sad"),
    ("competitive exam ki tayyari nahi ho rahi", "sad"), ("cant prepare for competitive exam", "sad"),
    ("friends sab select ho gaye main reh gaya", "sad"), ("all friends got selected except me", "sad"),
    ("placement nahi ho rahi", "sad"), ("i am not getting placed", "sad"),
    ("interview mein reject ho gaya", "sad"), ("i got rejected in interview", "sad"),
    ("project submit nahi hua time pe", "sad"), ("project was not submitted on time", "sad"),
    ("assignment pending hai bohot", "sad"), ("too many pending assignments", "sad"),
    ("padhai kaise karu samajh nahi aa raha", "sad"), ("i dont know how to study", "sad"),
    ("topper se compare karte hain sab", "sad"), ("everyone compares me with topper", "sad"),
    ("maths samajh nahi aata", "sad"), ("i dont understand maths", "sad"),
    ("viva mein kuch nahi bola paya", "sad"), ("i couldnt say anything in viva", "sad"),
    ("practical mein galti ho gayi", "sad"), ("i made a mistake in practical", "sad"),
    ("attendance kam hai", "sad"), ("my attendance is low", "sad"),
    ("college jaane ka mann nahi karta", "sad"), ("i dont feel like going to college", "sad"),
    ("drop lena chahiye kya", "sad"), ("should i take a drop year", "sad"),
    ("year loss ho jayega", "sad"), ("i might lose a year", "sad"),
    ("kisi cheez mein interest nahi raha", "sad"), ("i have lost interest in everything", "sad"),
    ("career ka kuch pata nahi", "sad"), ("i dont know about my career", "sad"),
    ("future dark lagta hai padhai ki wajah se", "sad"), ("future looks dark due to studies", "sad"),
    ("mujhse padhai nahi hoti", "sad"), ("i just cant study", "sad"),
    ("padhai chhodna chahta hu", "sad"), ("i want to quit studies", "sad"),
    ("fail hone ka darr khata ja raha hai", "sad"), ("fear of failure is consuming me", "sad"),
    ("sab log judge karte hain marks dekh ke", "sad"), ("everyone judges by marks", "sad"),
    ("mummy papa ke expectations puri nahi kar pa raha", "sad"), ("cant meet parents expectations", "sad"),
    ("scholarship chali gayi", "sad"), ("i lost my scholarship", "sad"),
    ("hostel mein padhai nahi ho pati", "sad"), ("cant study in hostel", "sad"),
    ("roommate disturb karta hai", "sad"), ("roommate disturbs me", "sad"),
    ("library mein jagah nahi milti", "sad"), ("no space in library", "sad"),
    ("online classes samajh nahi aati", "sad"), ("i dont understand online classes", "sad"),
    ("notes nahi hain", "sad"), ("i dont have notes", "sad"),
    ("exam hall mein anxiety hoti hai", "sad"), ("i get anxiety in exam hall", "sad"),
]

# TOPIC 5: LONELINESS & ISOLATION (100 questions)
loneliness = [
    ("bohot akela feel hota hai", "sad"), ("i feel so lonely", "sad"),
    ("koi mere saath nahi hai", "sad"), ("nobody is with me", "sad"),
    ("mera koi dost nahi hai", "sad"), ("i have no friends", "sad"),
    ("sab ne mujhe chhod diya", "sad"), ("everyone has left me", "sad"),
    ("koi baat nahi karta mujhse", "sad"), ("nobody talks to me", "sad"),
    ("akele rehna pad raha hai", "sad"), ("i have to live alone", "sad"),
    ("hostel mein bohot akela lagta hai", "sad"), ("i feel very lonely in hostel", "sad"),
    ("ghar ki yaad aa rahi hai", "sad"), ("i miss home", "sad"),
    ("koi samajhta nahi mujhe", "sad"), ("nobody understands me", "sad"),
    ("main invisible hu sab ke liye", "sad"), ("i am invisible to everyone", "sad"),
    ("group mein bhi akela lagta hu", "sad"), ("i feel alone even in a group", "sad"),
    ("mera phone kabhi nahi bajta", "sad"), ("my phone never rings", "sad"),
    ("social media pe sab ke dost hain mere nahi", "sad"), ("everyone has friends on social media except me", "sad"),
    ("birthday pe kisi ne wish nahi kiya", "sad"), ("nobody wished me on my birthday", "sad"),
    ("canteen mein akela baithta hu", "sad"), ("i sit alone in canteen", "sad"),
    ("project ke liye koi partner nahi mila", "sad"), ("no partner for project", "sad"),
    ("fest mein koi saath nahi gaya", "sad"), ("nobody went to fest with me", "sad"),
    ("roommate bhi ignore karta hai", "sad"), ("even my roommate ignores me", "sad"),
    ("class mein koi baat nahi karta", "sad"), ("nobody talks to me in class", "sad"),
    ("lunch akele khata hu roz", "sad"), ("i eat lunch alone every day", "sad"),
    ("mujhe lag raha hai main bore hu sabko", "sad"), ("i think i bore everyone", "sad"),
    ("log mujhse distance banate hain", "sad"), ("people keep distance from me", "sad"),
    ("mujhme koi qualities nahi hain dosti ke liye", "sad"), ("i have no qualities for friendship", "sad"),
    ("main introvert hu isliye koi nahi chahta", "sad"), ("nobody wants me because i am introvert", "sad"),
    ("gharwaale bhi busy hain mere liye", "sad"), ("even family is too busy for me", "sad"),
    ("maa se baat karna chahta hu par nahi kar pata", "sad"), ("i want to talk to mom but cant", "sad"),
    ("papa se rishta achha nahi hai", "sad"), ("i dont have good relation with dad", "sad"),
    ("bhai behen bhi apni duniya mein hain", "sad"), ("siblings are in their own world", "sad"),
    ("ek pal bhi achi company nahi milti", "sad"), ("i never get good company", "sad"),
    ("khud se baat karta hu akele mein", "sad"), ("i talk to myself when alone", "sad"),
    ("deewar se baat karna padta hai", "sad"), ("i end up talking to walls", "sad"),
    ("koi mera intezaar nahi karta", "sad"), ("nobody waits for me", "sad"),
    ("mujhe lagta hai main ek outsider hu", "sad"), ("i feel like an outsider", "sad"),
    ("belonging feel nahi hota kahin", "sad"), ("i dont feel i belong anywhere", "sad"),
    ("mujhe abandon kar diya sabne", "sad"), ("everyone has abandoned me", "sad"),
    ("trust karne se darr lagta hai", "sad"), ("i am afraid to trust", "sad"),
    ("log dhoka dete hain", "sad"), ("people betray me", "sad"),
    ("mujhse pyar koi nahi karta", "sad"), ("nobody loves me", "sad"),
    ("koi hug bhi nahi karta", "sad"), ("nobody even hugs me", "sad"),
    ("raat ko sab so jaate hain main jagta rehta hu", "sad"), ("everyone sleeps at night i stay awake", "sad"),
    ("weekend pe bhi koi plan nahi hota", "sad"), ("no plans even on weekends", "sad"),
    ("akele ghar pe baitha rehta hu", "sad"), ("i just sit alone at home", "sad"),
    ("bahar jaane ka mann nahi karta", "sad"), ("i dont feel like going out", "sad"),
    ("social gatherings mein uncomfortable lagta hai", "sad"), ("i feel uncomfortable at social gatherings", "sad"),
    ("mujhe lagta hai log mujhe pasand nahi karte", "sad"), ("i feel people dont like me", "sad"),
]

# TOPIC 6: RELATIONSHIP & HEARTBREAK (100 questions)
relationship = [
    ("mera breakup ho gaya", "sad"), ("i just had a breakup", "sad"),
    ("usne mujhe dhoka diya", "sad"), ("they cheated on me", "sad"),
    ("mera dil toot gaya hai", "sad"), ("my heart is broken", "sad"),
    ("pyar mein dhoka mila", "sad"), ("i was betrayed in love", "sad"),
    ("ex ko bhool nahi pa raha", "sad"), ("i cant forget my ex", "sad"),
    ("woh mujhse baat nahi karti", "sad"), ("she doesnt talk to me", "sad"),
    ("woh kisi aur ke saath hai ab", "sad"), ("they are with someone else now", "sad"),
    ("mujhe laga woh mera tha", "sad"), ("i thought they were mine", "sad"),
    ("pyar mein sab kuch de diya", "sad"), ("i gave everything in love", "sad"),
    ("trust tod diya usne", "sad"), ("they broke my trust", "sad"),
    ("block kar diya mujhe", "sad"), ("they blocked me", "sad"),
    ("roz unki yaad aati hai", "sad"), ("i miss them every day", "sad"),
    ("unke bina zindagi adhuri lagti hai", "sad"), ("life feels incomplete without them", "sad"),
    ("kaise bhulu unhe", "sad"), ("how do i forget them", "sad"),
    ("move on nahi ho pa raha", "sad"), ("i cant move on", "sad"),
    ("sab couple hain main akela", "sad"), ("everyone is in a couple i am alone", "sad"),
    ("valentine day pe akela hu", "sad"), ("alone on valentine day", "sad"),
    ("proposal reject ho gaya", "sad"), ("my proposal got rejected", "sad"),
    ("crush ne friendzone kar diya", "sad"), ("crush friendzoned me", "sad"),
    ("one sided love hai", "sad"), ("it is one sided love", "sad"),
    ("pyar karna galat tha kya", "sad"), ("was it wrong to love", "sad"),
    ("kitna dard hota hai breakup mein", "sad"), ("how painful a breakup is", "sad"),
    ("rona band nahi ho raha breakup ke baad", "sad"), ("cant stop crying after breakup", "sad"),
    ("unke saath jo time spend kiya woh yaad aata hai", "sad"), ("i remember the time spent together", "sad"),
    ("unka number delete nahi kar pa raha", "sad"), ("i cant delete their number", "sad"),
    ("unke photos dekh ke rona aata hai", "sad"), ("i cry looking at their photos", "sad"),
    ("pyar mein vishwas nahi raha", "sad"), ("i dont believe in love anymore", "sad"),
    ("relationship toxic thi", "sad"), ("the relationship was toxic", "sad"),
    ("usne manipulate kiya mujhe", "sad"), ("they manipulated me", "sad"),
    ("possessive tha woh bohot", "sad"), ("they were very possessive", "sad"),
    ("abusive relationship thi", "sad"), ("it was an abusive relationship", "sad"),
    ("use kisi ne bhi nahi roka", "sad"), ("nobody stopped them", "sad"),
    ("meri galti nahi thi phir bhi", "sad"), ("it wasnt my fault still", "sad"),
    ("dusri baar bhi dhoka mila", "sad"), ("got cheated for the second time", "sad"),
    ("ab kisi pe bharosa nahi hoga", "sad"), ("i wont trust anyone now", "sad"),
    ("pyar ek dhoka hai", "sad"), ("love is a lie", "sad"),
    ("unke bina raat nahi katti", "sad"), ("nights are tough without them", "sad"),
    ("gaano mein unki yaad aati hai", "sad"), ("songs remind me of them", "sad"),
    ("har jagah unki yaadein hain", "sad"), ("their memories are everywhere", "sad"),
    ("mujhe lagta hai main deserve nahi karta pyar", "sad"), ("i feel i dont deserve love", "sad"),
    ("kya mujhse koi pyar karega kabhi", "sad"), ("will anyone ever love me", "sad"),
    ("relationship mein bohot hurt hua hu", "sad"), ("i have been very hurt in relationship", "sad"),
    ("dosti bhi kharab ho gayi uski wajah se", "sad"), ("even friendships got ruined because of them", "sad"),
    ("mutual friends ne side le liya", "sad"), ("mutual friends took sides", "sad"),
    ("ab kisi se baat karne ka mann nahi karta", "sad"), ("dont feel like talking to anyone now", "sad"),
    ("pyar mein pagal ho gaya tha", "sad"), ("i was crazy in love", "sad"),
]

# TOPIC 7: ABUSE & SAFETY (100 questions)
abuse = [
    ("mera sath molestation hua hai", "critical"), ("i have been molested", "critical"),
    ("kisi ne mujhe touch kiya galat tarike se", "critical"), ("someone touched me inappropriately", "critical"),
    ("ghar pe relative ne gandi harkat ki", "critical"), ("a relative did bad things at home", "critical"),
    ("mujhe bully kiya jaata hai", "critical"), ("i am being bullied", "critical"),
    ("ragging ho rahi hai college mein", "critical"), ("ragging is happening in college", "critical"),
    ("zabardasti ki gayi mere saath", "critical"), ("i was forced", "critical"),
    ("mujhe maara jaata hai ghar pe", "critical"), ("i am beaten at home", "critical"),
    ("papa bohot maarte hain", "critical"), ("dad beats me a lot", "critical"),
    ("domestic violence ho rahi hai", "critical"), ("there is domestic violence", "critical"),
    ("mujhe daraya dhamkaya jaata hai", "critical"), ("i am threatened and scared", "critical"),
    ("sexual harassment hua hai", "critical"), ("i faced sexual harassment", "critical"),
    ("eve teasing hoti hai daily", "critical"), ("eve teasing happens daily", "critical"),
    ("koi mera peecha karta hai", "critical"), ("someone is stalking me", "critical"),
    ("online harassment ho rahi hai", "critical"), ("i am being harassed online", "critical"),
    ("mere photos leak kiye gaye", "critical"), ("my photos were leaked", "critical"),
    ("blackmail kiya ja raha hai mujhe", "critical"), ("i am being blackmailed", "critical"),
    ("mujhe gandi gaaliyan di jaati hain", "critical"), ("i am abused with bad words", "critical"),
    ("teacher ne galat tarike se touch kiya", "critical"), ("teacher touched inappropriately", "critical"),
    ("seniors ragging karte hain", "critical"), ("seniors do ragging", "critical"),
    ("maine galat kaam kiya hai", "critical"), ("bad things happened to me", "critical"),
    ("safe nahi hu main yahan", "critical"), ("i am not safe here", "critical"),
    ("mujhe protection chahiye", "critical"), ("i need protection", "critical"),
    ("koi meri help nahi karta", "critical"), ("nobody helps me", "critical"),
    ("police ko batau kya", "critical"), ("should i tell the police", "critical"),
    ("ghar jaane mein darr lagta hai", "critical"), ("i am scared to go home", "critical"),
    ("akele rehne mein darr lagta hai", "critical"), ("i am scared to be alone", "critical"),
    ("chacha ne galat kaam kiya", "critical"), ("uncle did wrong things", "critical"),
    ("mama ne mujhe molest kiya", "critical"), ("mama molested me", "critical"),
    ("padosi ne chheda", "critical"), ("neighbor harassed me", "critical"),
    ("auto wale ne galat touch kiya", "critical"), ("auto driver touched inappropriately", "critical"),
    ("school mein bully karte hain sab", "critical"), ("everyone bullies me at school", "critical"),
    ("cyber bullying ho rahi hai", "critical"), ("i am being cyber bullied", "critical"),
    ("meri marzi ke bina hua", "critical"), ("it happened without my consent", "critical"),
    ("kisi ko bata nahi sakti", "critical"), ("i cant tell anyone", "critical"),
    ("sharam aati hai batane mein", "critical"), ("i feel ashamed to tell", "critical"),
    ("meri galti nahi hai par log nahi manenge", "critical"), ("its not my fault but people wont believe", "critical"),
    ("log kya kahenge", "critical"), ("what will people say", "critical"),
    ("proof nahi hai mere paas", "critical"), ("i have no proof", "critical"),
    ("woh powerful hai main nahi", "critical"), ("they are powerful i am not", "critical"),
    ("mera mama ne mera mollestation kiya hai", "critical"),
    ("mera sath kisi ne galat kam kiya hai", "critical"),
    ("molestation hua mere sath", "critical"), ("mujhe mollest kiya gaya", "critical"),
    ("gandi harkat hui mere saath", "critical"), ("bad things happened to me", "critical"),
    ("kisi ne zabardasti ki mere saath", "critical"), ("someone forced me", "critical"),
    ("mujhe bahut maara gaya", "critical"), ("i was beaten badly", "critical"),
]

# TOPIC 8: SLEEP & INSOMNIA (80 questions)
sleep = [
    ("neend nahi aa rahi", "sad"), ("i cant sleep", "sad"),
    ("raat bhar jaagne lagta hu", "sad"), ("i stay awake all night", "sad"),
    ("insomnia hai mujhe", "sad"), ("i have insomnia", "sad"),
    ("sone ki koshish karta hu par nahi hota", "sad"), ("i try to sleep but cant", "sad"),
    ("3-4 ghante hi so pata hu", "sad"), ("i only sleep 3-4 hours", "sad"),
    ("subah uthne mein bahut mushkil hoti hai", "sad"), ("very difficult to wake up", "sad"),
    ("puri raat phone chalata rehta hu", "sad"), ("i use phone all night", "sad"),
    ("overthinking ki wajah se neend nahi aati", "sad"), ("cant sleep due to overthinking", "sad"),
    ("darr ki wajah se neend nahi aati", "sad"), ("cant sleep due to fear", "sad"),
    ("bure sapne aate hain", "sad"), ("i get nightmares", "sad"),
    ("raat ko baar baar uth jata hu", "sad"), ("i keep waking up at night", "sad"),
    ("neend ki goliyan le raha hu", "sad"), ("i am taking sleeping pills", "sad"),
    ("thaka rehta hu din bhar", "sad"), ("i feel tired all day", "sad"),
    ("energy nahi hai kuch karne ki", "sad"), ("no energy to do anything", "sad"),
    ("so ke uthta hu phir bhi thaka rehta hu", "sad"), ("i wake up still tired", "sad"),
    ("circadian rhythm bigad gaya hai", "sad"), ("my circadian rhythm is messed up", "sad"),
    ("raat ko 4 baje neend aati hai", "sad"), ("i fall asleep at 4am", "sad"),
    ("afternoon nap le leta hu phir raat ko nahi so pata", "sad"), ("afternoon nap ruins night sleep", "sad"),
    ("melatonin try karu kya", "sad"), ("should i try melatonin", "sad"),
    ("sleep cycle kaise theek karu", "sad"), ("how to fix sleep cycle", "sad"),
    ("sar dard hota hai neend na aane se", "sad"), ("headache from not sleeping", "sad"),
    ("aankhen jal rahi hain", "sad"), ("my eyes are burning", "sad"),
    ("concentration kam ho gayi hai neend ki wajah se", "sad"), ("concentration dropped due to sleep", "sad"),
    ("bohot irritable ho gaya hu neend nahi aane se", "sad"), ("very irritable from insomnia", "sad"),
    ("din mein susta rehta hu", "sad"), ("i feel lazy during daytime", "sad"),
    ("coffee se bhi kuch nahi hota", "sad"), ("even coffee doesnt help", "sad"),
    ("raat ko anxiety badhti hai", "sad"), ("anxiety increases at night", "sad"),
    ("sone se pehle bohot overthink karta hu", "sad"), ("i overthink before sleeping", "sad"),
    ("neend mein baat karta hu", "sad"), ("i talk in my sleep", "sad"),
    ("sleep paralysis hota hai", "sad"), ("i get sleep paralysis", "sad"),
    ("bohot restless rehti hai neend", "sad"), ("my sleep is very restless", "sad"),
    ("raat ko kaamp ke uth jaata hu", "sad"), ("i wake up trembling at night", "sad"),
    ("neend mein rota hu", "sad"), ("i cry in my sleep", "sad"),
    ("bohot zyada so raha hu", "sad"), ("i am sleeping too much", "sad"),
    ("12 ghante sone ke baad bhi thakan hai", "sad"), ("still tired after 12 hours of sleep", "sad"),
]

# TOPIC 9: HAPPY / POSITIVE (100 questions)
happy = [
    ("aaj bohot achha din hai", "happy"), ("today is a great day", "happy"),
    ("bohot khush hu main", "happy"), ("i am very happy", "happy"),
    ("life is going great", "happy"), ("zindagi mein sab badhiya chal raha hai", "happy"),
    ("exam mein achhe marks aaye", "happy"), ("i got good marks in exam", "happy"),
    ("placement ho gayi meri", "happy"), ("i got placed", "happy"),
    ("promotion mil gayi", "happy"), ("i got a promotion", "happy"),
    ("dost se milke bohot achha laga", "happy"), ("felt great meeting a friend", "happy"),
    ("mummy ka khaana kha liya bohot maza aaya", "happy"), ("ate moms food it was great", "happy"),
    ("cricket jeet gaye hum", "happy"), ("we won the cricket match", "happy"),
    ("new phone mila", "happy"), ("i got a new phone", "happy"),
    ("first salary aayi", "happy"), ("got my first salary", "happy"),
    ("best day of my life", "happy"), ("aaj life ka sabse achha din tha", "happy"),
    ("sab kuch perfect chal raha hai", "happy"), ("everything is going perfect", "happy"),
    ("bohot excited hu", "happy"), ("i am very excited", "happy"),
    ("college fest mein prize jeeta", "happy"), ("i won a prize at college fest", "happy"),
    ("coding competition jeet gaya", "happy"), ("i won the coding competition", "happy"),
    ("internship mil gayi", "happy"), ("i got an internship", "happy"),
    ("crush ne haan bol diya", "happy"), ("crush said yes", "happy"),
    ("bohot mazedaar movie dekhi", "happy"), ("watched a very fun movie", "happy"),
    ("friends ke saath trip pe gaya", "happy"), ("went on a trip with friends", "happy"),
    ("ghar ja raha hu bohot khushi hai", "happy"), ("going home very happy", "happy"),
    ("festival ki bohot masti hai", "happy"), ("having a lot of fun at festival", "happy"),
    ("naya record banaya", "happy"), ("i made a new record", "happy"),
    ("teacher ne appreciate kiya", "happy"), ("teacher appreciated me", "happy"),
    ("mummy bohot proud hain", "happy"), ("mom is very proud", "happy"),
    ("papa ne gift diya", "happy"), ("dad gave me a gift", "happy"),
    ("dost ne surprise diya", "happy"), ("friend gave me a surprise", "happy"),
    ("life is lit bhai", "happy"), ("zindagi jhand nahi hai aaj", "happy"),
    ("bohot positive feel ho raha hai", "happy"), ("feeling very positive", "happy"),
    ("confidence badh gaya hai", "happy"), ("my confidence has increased", "happy"),
    ("gym se aa ke bohot achha lagta hai", "happy"), ("feel great after gym", "happy"),
    ("meditation karne se peace milta hai", "happy"), ("meditation gives me peace", "happy"),
    ("naya hobby start kiya bohot mazaa aa raha hai", "happy"), ("started a new hobby loving it", "happy"),
    ("painting kar raha hu bohot relaxing hai", "happy"), ("painting is very relaxing", "happy"),
    ("music sunke mood achha ho gaya", "happy"), ("music improved my mood", "happy"),
    ("aaj raat ko party hai", "happy"), ("there is a party tonight", "happy"),
    ("dosti bohot strong hai hamari", "happy"), ("our friendship is very strong", "happy"),
    ("achha khaana khaya bohot tasty tha", "happy"), ("ate good food very tasty", "happy"),
    ("sunset dekh ke mann khush ho gaya", "happy"), ("watching sunset made me happy", "happy"),
    ("bike ride pe gaya bohot maza aaya", "happy"), ("went for a bike ride had fun", "happy"),
    ("gaming mein bohot mazaa aa raha hai", "happy"), ("having a lot of fun gaming", "happy"),
    ("naye dost bane college mein", "happy"), ("made new friends at college", "happy"),
    ("result achha aaya relief hai", "happy"), ("result was good what a relief", "happy"),
    ("sab theek ho gaya hai ab", "happy"), ("everything is fine now", "happy"),
    ("thoda better feel ho raha hai", "happy"), ("feeling a bit better now", "happy"),
]

# TOPIC 10: OUT-OF-CONTEXT / CHITCHAT (100 questions)
chitchat = [
    ("aaj ka mausam kaisa hai", "out_of_context"), ("how is the weather today", "out_of_context"),
    ("kya time hua hai", "out_of_context"), ("what time is it", "out_of_context"),
    ("tumhara naam kya hai", "out_of_context"), ("what is your name", "out_of_context"),
    ("bhai biryani khani hai", "out_of_context"), ("i want to eat biryani", "out_of_context"),
    ("ipl mein kaun jeetega", "out_of_context"), ("who will win ipl", "out_of_context"),
    ("aaj ka match kaisa tha", "out_of_context"), ("how was todays match", "out_of_context"),
    ("pizza ya burger", "out_of_context"), ("pizza or burger", "out_of_context"),
    ("kaunsa phone lena chahiye", "out_of_context"), ("which phone should i buy", "out_of_context"),
    ("python kaise sikhu", "out_of_context"), ("how to learn python", "out_of_context"),
    ("coding kaise karu", "out_of_context"), ("how to code", "out_of_context"),
    ("hello bhai", "out_of_context"), ("hello", "out_of_context"),
    ("hi kaise ho", "out_of_context"), ("hey there", "out_of_context"),
    ("namaste", "out_of_context"), ("good morning", "out_of_context"),
    ("kya chal raha hai", "out_of_context"), ("whats up", "out_of_context"),
    ("bye bhai", "out_of_context"), ("see you later", "out_of_context"),
    ("tata", "out_of_context"), ("goodbye", "out_of_context"),
    ("kya kar raha hai tu", "out_of_context"), ("what are you doing", "out_of_context"),
    ("aaj kya khaoge", "out_of_context"), ("what will you eat today", "out_of_context"),
    ("favourite movie kaunsi hai", "out_of_context"), ("whats your favourite movie", "out_of_context"),
    ("mujhe coding sikhao", "out_of_context"), ("teach me coding", "out_of_context"),
    ("2 plus 2 kitna hota hai", "out_of_context"), ("what is 2 plus 2", "out_of_context"),
    ("capital of india kya hai", "out_of_context"), ("what is capital of india", "out_of_context"),
    ("tum robot ho ya insaan", "out_of_context"), ("are you a robot or human", "out_of_context"),
    ("kya tum real ho", "out_of_context"), ("are you real", "out_of_context"),
    ("poem sunao", "out_of_context"), ("tell me a poem", "out_of_context"),
    ("story sunao", "out_of_context"), ("tell me a story", "out_of_context"),
    ("game khelna hai", "out_of_context"), ("i want to play a game", "out_of_context"),
    ("cricket ka score kya hai", "out_of_context"), ("whats the cricket score", "out_of_context"),
    ("aaj konsa din hai", "out_of_context"), ("what day is it today", "out_of_context"),
    ("tumhe kya pasand hai", "out_of_context"), ("what do you like", "out_of_context"),
    ("tum kitne saal ke ho", "out_of_context"), ("how old are you", "out_of_context"),
    ("kya tum sach bolte ho", "out_of_context"), ("do you tell the truth", "out_of_context"),
    ("aaj bohot garmi hai", "out_of_context"), ("it is very hot today", "out_of_context"),
    ("barish ho rahi hai", "out_of_context"), ("it is raining", "out_of_context"),
    ("chai peena hai", "out_of_context"), ("i want tea", "out_of_context"),
    ("maggi banani hai", "out_of_context"), ("i want to make maggi", "out_of_context"),
    ("laptop kaunsa loon", "out_of_context"), ("which laptop should i get", "out_of_context"),
    ("exam kab hai", "out_of_context"), ("when is the exam", "out_of_context"),
    ("tum hindi samajhte ho", "out_of_context"), ("do you understand hindi", "out_of_context"),
    ("ek shayari sunao", "out_of_context"), ("recite a poetry", "out_of_context"),
    ("ai kya hota hai", "out_of_context"), ("what is ai", "out_of_context"),
    ("chatgpt better hai ya tum", "out_of_context"), ("is chatgpt better or you", "out_of_context"),
    ("bhai kya scene hai", "out_of_context"), ("bro whats the scene", "out_of_context"),
    ("netflix pe kya dekhu", "out_of_context"), ("what to watch on netflix", "out_of_context"),
    ("konsi book padhun", "out_of_context"), ("which book should i read", "out_of_context"),
    ("hogwarts mein kaunsa house", "out_of_context"), ("which hogwarts house", "out_of_context"),
    ("avengers ya justice league", "out_of_context"), ("avengers or justice league", "out_of_context"),
]

# TOPIC: FAMILY PRESSURE (80 questions)
family = [
    ("ghar pe bohot ladai hoti hai", "sad"), ("there are lots of fights at home", "sad"),
    ("mummy papa ka roz jhagda hota hai", "sad"), ("parents fight every day", "sad"),
    ("papa bohot strict hain", "sad"), ("dad is very strict", "sad"),
    ("mummy samajhti nahi hai", "sad"), ("mom doesnt understand", "sad"),
    ("parents ka pressure bohot hai", "sad"), ("too much parental pressure", "sad"),
    ("ghar pe koi support nahi karta", "sad"), ("no support at home", "sad"),
    ("papa ne maara aaj", "sad"), ("dad hit me today", "sad"),
    ("mummy roz daantii hai", "sad"), ("mom scolds me every day", "sad"),
    ("bhai se comparison hoti hai", "sad"), ("i am compared with brother", "sad"),
    ("cousin se compare karte hain", "sad"), ("i am compared with cousin", "sad"),
    ("padosi ke bete se compare karte hain", "sad"), ("compared with neighbors son", "sad"),
    ("gharwaale samajhte nahi mental health", "sad"), ("family doesnt understand mental health", "sad"),
    ("papa ko lagta hai depression fake hai", "sad"), ("dad thinks depression is fake", "sad"),
    ("mummy kehti hai drama kar raha hai", "sad"), ("mom says i am doing drama", "sad"),
    ("ghar mein baat sunne wala koi nahi", "sad"), ("nobody listens at home", "sad"),
    ("papa ka gussa bohot aata hai", "sad"), ("dads anger is too much", "sad"),
    ("family mein koi pyar nahi hai", "sad"), ("there is no love in family", "sad"),
    ("ghar toxic hai", "sad"), ("home is toxic", "sad"),
    ("parents ka divorce ho raha hai", "sad"), ("parents are getting divorced", "sad"),
    ("papa ghar nahi aate", "sad"), ("dad doesnt come home", "sad"),
    ("mummy bohot roti hai", "sad"), ("mom cries a lot", "sad"),
    ("dada dadi ka pressure hai shaadi ka", "sad"), ("grandparents pressure for marriage", "sad"),
    ("family expectations bohot zyada hain", "sad"), ("family expectations are too high", "sad"),
    ("ghar se bhaag jaana chahta hu", "sad"), ("i want to run away from home", "sad"),
    ("papa se darr lagta hai", "sad"), ("i am scared of dad", "sad"),
    ("ghar jaane ka mann nahi karta", "sad"), ("i dont want to go home", "sad"),
    ("parents ne decision thop diya", "sad"), ("parents forced their decision on me", "sad"),
    ("meri choice ko koi value nahi deta", "sad"), ("nobody values my choices", "sad"),
    ("bohot suffocating hai ghar", "sad"), ("home is very suffocating", "sad"),
    ("papa sharaab peete hain", "sad"), ("dad drinks alcohol", "sad"),
    ("ghar mein paise ki bohot dikkat hai", "sad"), ("financial problems at home", "sad"),
    ("fees ke paise nahi hain", "sad"), ("no money for fees", "sad"),
    ("loan ki tension hai ghar mein", "sad"), ("loan stress at home", "sad"),
    ("papa ki health kharab hai", "sad"), ("dads health is bad", "sad"),
    ("mummy hospital mein hai", "sad"), ("mom is in hospital", "sad"),
]

# Combine all questions
ALL_QUESTIONS = (
    [("depression", q, e) for q, e in depression] +
    [("crisis", q, e) for q, e in crisis] +
    [("anxiety", q, e) for q, e in anxiety] +
    [("academic", q, e) for q, e in academic] +
    [("loneliness", q, e) for q, e in loneliness] +
    [("relationship", q, e) for q, e in relationship] +
    [("abuse", q, e) for q, e in abuse] +
    [("sleep", q, e) for q, e in sleep] +
    [("happy", q, e) for q, e in happy] +
    [("chitchat", q, e) for q, e in chitchat] +
    [("family", q, e) for q, e in family]
)

if __name__ == "__main__":
    print(f"Total test questions: {len(ALL_QUESTIONS)}")
    topics = {}
    for topic, q, e in ALL_QUESTIONS:
        topics[topic] = topics.get(topic, 0) + 1
    for t, c in sorted(topics.items(), key=lambda x: -x[1]):
        print(f"  {t}: {c}")
